### ISSUE TITLE
Error in Firefox and IE11

### ISSUE THREAD

**Issue by abhinaba1080** [alfonso-presa/protractor-testability-plugin#12]
Hi @alfonso-presa 

The plugin works great in Chrome, but for same test case I am getting below error in Firefox and IE11

```
 Fail:  protractor-testability-plugin Plugin Tests 
logger.js:158
[12:18:12] E/plugins - 		Failure during waitForPromise: Timed out after 110000 ms
logger.js:158
[12:18:12] E/plugins - 		ScriptTimeoutError: Timed out after 110000 ms
		    at Object.throwDecodedError (C:\Dev Room\Projects\Demo\node_modules\selenium-webdriver\lib\error.js:514:15)
		    at parseHttpResponse (C:\Dev Room\Projects\Demo\node_modules\selenium-webdriver\lib\http.js:519:13)
		    at execute.request.then.doSend.then.response (C:\Dev Room\Projects\Demo\node_modules\selenium-webdriver\lib\http.js:441:30)
		    at process._tickCallback (internal/process/next_tick.js:68:7)
		From: Task: WebDriver.executeScript()
		    at Driver.schedule (C:\Dev Room\Projects\Demo\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
		    at Driver.executeAsyncScript (C:\Dev Room\Projects\Demo\node_modules\selenium-webdriver\lib\webdriver.js:891:17)
		    at run (C:\Dev Room\Projects\Demo\node_modules\protractor\built\browser.js:59:33)
		    at ProtractorBrowser.to.(anonymous function) [as executeAsyncScript] (C:\Dev Room\Projects\Demo\node_modules\protractor\built\browser.js:67:16)
		    at Object.waitForPromise (C:\Dev Room\Projects\Demo\node_modules\protractor-testability-plugin\dist\protractor-testability-plugin.js:52:24)
		    at resolver (C:\Dev Room\Projects\Demo\node_modules\protractor\built\plugins.js:194:51)
		    at new ManagedPromise (C:\Dev Room\Projects\Demo\node_modules\selenium-webdriver\lib\promise.js:1077:7)
		    at Plugins.safeCallPluginFun (C:\Dev Room\Projects\Demo\node_modules\protractor\built\plugins.js:210:20)
		    at pluginFunFactory.promises.pluginObjs.filter.map.pluginObj (C:\Dev Room\Projects\Demo\node_modules\protractor\built\plugins.js:219:40)
		    at Array.map (<anonymous>)
		    at Plugins.pluginFunFactory.args [as waitForPromise] (C:\Dev Room\Projects\Demo\node_modules\protractor\built\plugins.js:219:18)
		    at waitForAngular.runWaitForAngularScript.then.then.driver.controlFlow.execute (C:\Dev Room\Projects\Demo\node_modules\protractor\built\browser.js:470:38)
		    at TaskQueue.execute_ (C:\Dev Room\Projects\Demo\node_modules\selenium-webdriver\lib\promise.js:3084:14)
		    at TaskQueue.executeNext_ (C:\Dev Room\Projects\Demo\node_modules\selenium-webdriver\lib\promise.js:3067:27)
		    at start.asyncRun (C:\Dev Room\Projects\Demo\node_modules\selenium-webdriver\lib\promise.js:2974:25)
		    at C:\Dev Room\Projects\Demo\node_modules\selenium-webdriver\lib\promise.js:668:7
```
I am using directConnct for Firefox.

**Comment by abhinaba1080** [comment]
hi @alfonso-presa , any update on that?

**Comment by abhinaba1080** [comment]
@alfonso-presa : This is a real blocker for me. Let me know if this is something that can be fixed.

**Comment by alfonso-presa** [comment]
Hi @abhinaba1080,

I've not found the time to look into this. I would say that your application has some background process (long polling or similar) that is causing the testability to never get to a relaxed state. I cannot tell without having access to the application. I recommend you to review the application requests to see if there's something being requested that doesn't get response or that's always pending. This may also happen if you have any background timeouts or continuous animations.

As said, I would not be able to provide more information unless you provide an isolated way to reproduce the issue.

**Comment by abhinaba1080** [comment]
Thanks, @alfonso-presa . I will have a look at this. But I was able to run the same test in chrome without any problem. It is highly unlikely that the same application has different calls based on browsers.

**Comment by alfonso-presa** [comment]
@abhinaba1080, I don't know the application, but depending on the version of firefox or the frameworks you're using it would not be weird to see some fallback on websockets to long polling or of some animation being performed by javascript instead of animations api....
